fix typo; add back alembic migrations for db setup.

diff --git a/files/docker/Dockerfile b/files/docker/Dockerfile
--- a/files/docker/Dockerfile
+++ b/files/docker/Dockerfile
@@ -4,10 +4,10 @@ FROM quay.io/packit/base:fedora
 
 ARG SOURCE_BRANCH
 RUN  if [[ -z $SOURCE_BRANCH ]]; then \
-echo -e "\nMissing SOURCE_BRANCH build argument! Please add \
-\"--build-arg SOURCE_BRANCH=<val>\" to the build command to specify it!\n\
-This is the branch used when installing other Packit projects (e.g. ogr, packit).\n" && exit 1;\
-fi
+    echo -e "\nMissing SOURCE_BRANCH build argument! Please add \
+    \"--build-arg SOURCE_BRANCH=<val>\" to the build command to specify it!\n\
+    This is the branch used when installing other Packit projects (e.g. ogr, packit).\n" && exit 1;\
+    fi
 
 ENV USER=packit \
     HOME=/home/packit
@@ -23,11 +23,15 @@ COPY setup.py setup.cfg ./
 COPY .git ./.git
 COPY packit_service/ ./packit_service/
 
+
 RUN git rev-parse HEAD >/.packit-service.git.commit.hash \
     && git show --quiet --format=%B HEAD >/.packit-service.git.commit.message \
     && ansible-playbook -vv -c local -i localhost, files/recipe.yaml
 
 # no need to rm /src, it will stay in the image anyway
+
+COPY alembic.ini ./
+COPY alembic/ ./alembic/
 
 
 EXPOSE 8443
